### ISSUE TITLE
Package status

### ISSUE THREAD

**Issue by egolep** [gdkrmr/KernelRidgeRegression.jl#4]
Hi,
I was looking for a simple package for (kernel) ridge regression, something similar to DecisionTree.jl and I stepped on this project.
I see it's last update has been four years ago and I'm obviously not asking when the development will start again, instead I'm interested in:

- how does it work with modern Julia? Do you know what would need to be updated in order to work?
- how good were the performances? Could it work on a GPU?

Many thanks for your precious time if you will ever mind to answer the question of a noob who tries to be opinionated against big ML packages for Julia.

**Comment by gdkrmr** [comment]
Hi, thanks for the interest. The whole thing was a project for me to understand GPs and Kernel Regression and I am not maintaining it any more. The whole package was written before there was nice and performant syntax for Matrix multiplications, you can just replace all the BLAS calls with standard matrix operations now. Using standard matrix operations you should also be able to use everything wit CuArrays and you can just get rid of my failed attempt to make it work on a GPU.

**Comment by egolep** [comment]
So it looks like the situation is even better than what I expected. 
Thank you for your answer!

**Comment by gdkrmr** [comment]
No problem :+1: Take a look at Flux.jl, they use a lot of generic code that works with Arrays and CuArrays.
